# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\"T\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0fhashed_password\x18\x04 \x01(\t\"i\n\tUserReply\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0fhashed_password\x18\x04 \x01(\t\x12\x15\n\rresponse_code\x18\x05 \x01(\x05\x32\x86\x01\n\x0bUserService\x12%\n\x07GetUser\x12\x0c.UserRequest\x1a\n.UserReply\"\x00\x12&\n\x08PostUser\x12\x0c.UserRequest\x1a\n.UserReply\"\x00\x12(\n\nDeleteUser\x12\x0c.UserRequest\x1a\n.UserReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=22
  _USERREQUEST._serialized_end=106
  _USERREPLY._serialized_start=108
  _USERREPLY._serialized_end=213
  _USERSERVICE._serialized_start=216
  _USERSERVICE._serialized_end=350
# @@protoc_insertion_point(module_scope)
